import type { Metadata } from 'next';
import { PageModal } from '../ui/primitives/Modal/PageModal';

export const metadata: Metadata = {
  title: 'Todos',
  description: 'Generated by create next app',
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <PageModal>{children}</PageModal>;
}
